name: Build, Test, Publish and Deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'TailwindTraders.Website/**'
      - .github/workflows/github-actions-demo.yml
  pull_request:
    branches: [ main ]
    paths:
      - 'TailwindTraders.Website/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Harden Runner
      uses: step-security/harden-runner@128a63446a954579617e875aaab7d2978154e969 # v2.4.0
      with:
        egress-policy: audit

    - uses: actions/checkout@61b9e3751b92087fd0b06925ba6dd6314e06f089 # master

    - name: Setup Node
      uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e # v1.4.6
      with:
        node-version: 10.16.3    

    - name: Install dependencies in client app
      working-directory: TailwindTraders.Website/Source/Tailwind.Traders.Web/ClientApp
      run: npm install

    - name: Build and publish with dotnet
      working-directory: TailwindTraders.Website/Source
      run: |
        dotnet build --configuration Release

    - name: Run rests
      working-directory: TailwindTraders.Website/Source
      run: |
        dotnet test --logger "trx;LogFileName=test-results.trx" --configuration Release

    - name: Publish with dotnet
      working-directory: TailwindTraders.Website/Source
      run: |
        dotnet publish -c Release -o ${{github.workspace}}/myapp

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2.3.1
      with:
        name: .net-app
        path: ${{github.workspace}}/myapp
        
    - name: generate releasenotes
      uses: XpiritCommunityEvents/ReleasenoteAction@ac14eb13296e035839e9ded811e386d30e088a2c # main
      with:
          environment: ${{ toJSON(github) }}
          owner: XpiritCommunityEvents
          repo: ReleasenoteAction
          github_token: ${{ github.token }}
          labelname: releasenote
          markdownfile: releasenotes.md

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@128a63446a954579617e875aaab7d2978154e969 # v2.4.0
        with:
          egress-policy: audit

      - name: Download artifact from build job
        uses: actions/download-artifact@cbed621e49e4c01b044d60f6c80ea4ed6328b281 # v2.1.1
        with:
          name: .net-app
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@fb8292eb575db1bb18a90627e8959cd51dbb355c # v2.2.10
        with:
          app-name: 'web-demo-rob'
          slot-name: 'production'
          publish-profile: ${{ secrets.publish_profile }}
          package: .
